[package]
name = "memory_pool"
version.workspace = true
edition.workspace = true

[dependencies]
datafusion = { workspace = true }
async-backtrace = { workspace = true, optional = true }

[features]
default = []
backtrace = ["async-backtrace"]