[package]
name = "memory_pool"
version = "2.2.0"
edition = "2021"

[dependencies]
datafusion = { workspace = true }
async-backtrace = { workspace = true, optional = true }

[features]
default = []
backtrace = ["async-backtrace"]