id = 1
host = "127.0.0.1"
port = 8901
data_path = "/var/lib/cnosdb/meta"
cluster_name = "cluster_xxx"
grpc_enable_gzip = false

[log]
level = "info"
path = "/var/log/cnosdb"

[heartbeat]
heartbeat_recheck_interval = 300
heartbeat_expired_interval = 600
