[package]
name = "e2e_test"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-schema = { workspace = true, optional = false }
meta = { path = "../meta" }
models = { path = "../common/models" }
protos = { path = "../common/protos", features = ["test"] }
sysinfo = { workspace = true, optional = false }
regex = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
config = { path = "../config" }
http_protocol = { path = "../common/http_protocol", features = ["http_client"] }

arrow-flight = { workspace = true, features = ["flight-sql-experimental"] }
chrono = { workspace = true }
datafusion = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true, default-features = false, features = ["alloc"] }
protobuf = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
serial_test = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["tls", "transport"] }
walkdir = { workspace = true }
fly-accept-encoding = { workspace = true }

[features]
default = []
coordinator_e2e_test = []
not_passed = []
