[package]
name = "e2e_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.7.0"
protos = { path = "../common/protos", features = ["test"] }

[dev-dependencies]
http_protocol = { path = "../common/http_protocol", features = ["http_client"] }

flatbuffers = { workspace = true }
tonic = {version = "0.7", features = ["tls", "transport"]}
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"
