[package]
name = "e2e_test"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = { workspace = true }
protos = { path = "../common/protos", features = ["test"] }

[dev-dependencies]
http_protocol = { path = "../common/http_protocol", features = ["http_client"] }

flatbuffers = { workspace = true }
tonic = { workspace = true, features = ["tls", "transport"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
datafusion = { workspace = true }
arrow-flight = { workspace = true, features = ["flight-sql-experimental"] }
futures = { workspace = true, default-features = false, features = ["alloc"] }
