[workspace]

members = [
    "main"
]

default-members = ["main"]

[profile.dev]
lto = false
opt-level = 0
codegen-units = 16
debug-assertions = true
panic = 'unwind'
incremental = true
overflow-checks = true
debug = true

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
debug-assertions = false
panic = 'unwind'
incremental = false
overflow-checks = false
debug = false

[profile.test]
lto = false
opt-level = 0
codegen-units = 16
debug-assertions = true
panic = 'unwind'
incremental = true
overflow-checks = true
debug = 2

[profile.bench]
lto = false
opt-level = 3
codegen-units = 1
debug-assertions = false
panic = 'unwind'
incremental = false
overflow-checks = false
debug = false