[workspace]
members = [
    "common/models",
    "common/protos",
    "common/line_protocol",
    "common/metrics",
    "common/trace",
    "common/utils",
    "common/http_protocol",
    "common/error_code",
    "common/error_code/error_code_macro",
    "common/lru_cache",
    "common/limiter_bucket",
    "common/memory_pool",
    "query_server/spi",
    "query_server/query",
    "query_server/test",
    "e2e_test",
    "coordinator",
    "config",
    "meta",
    "tskv",
    "main",
    "client",
]
default-members = ["main"]

[workspace.dependencies]
actix-rt = "2.7.0"
actix-web = "4.0.0"
async-recursion = "1.0.0"
async-stream = "0.3"
async-trait = "0.1"
base64 = { version = "0.13" }
backtrace = "0.3"
backoff = "0.4"
bincode = "1.3.3"
blake3 = "1.3.3"
bytes = "1.1"
byteorder = "1.4.3"
bzip2 = "0.4.3"
chrono = "0.4"
clap = { version = "4", features = ["default", "derive"] }
color-eyre = "0.6"
core_affinity = "0.5.10"
crc32fast = "1.3.0"
criterion = { version = "0.3.5" }
crossbeam = "0.8"
crossbeam-channel = "0.5"
ctrlc = "3"
dashmap = "5.2"
derive_builder = "0.11"
arrow-schema = { version = "32.0.0", features = ["serde"] }
arrow-flight = { version = "32.0.0" }
datafusion-proto = { git = "https://github.com/cnosdb/arrow-datafusion.git", rev = "10a2325d6260c5f0251cfb1187e022c6607c6ef5" }
datafusion = { git = "https://github.com/cnosdb/arrow-datafusion.git", rev = "10a2325d6260c5f0251cfb1187e022c6607c6ef5" }
diff = "0.1.13"
dirs = "4.0.0"
env_logger = "0.9"
evmap = "10.0"
flatbuffers = "22.9"
flate2 = "1.0.24"
futures = { version = "0.3" }
integer-encoding = "3.0.3"
lazy_static = "1.4"
libc = { version = "0.2", default-features = false }
minivec = "0.4.0"
mio = "0.8"
moka = "0.9.6"
nom = "7.1.1"
num_cpus = "1.13.0"
num_enum = "0.5.7"
num-traits = "0.2.14"
once_cell = "1.12.0"
os_info = { version = "3" }
openssl = { version = "0.10.28", features = ["vendored"] }
object_store = { version = "0.5.2", features = ["aws", "gcp", "azure"] }
openraft = { git = "https://github.com/datafuselabs/openraft", rev = "914fcb4dad32a2f187b808298048e9e8b912977f", features = ["serde"] }
page_size = "0.4"
parking_lot = { version = "0.12" }
paste = "1.0"
pin-project = "1.0"
priority-queue = "1.2.3"
prost = "0.11.0"
prost-build = "0.11.0"
prost-types = { version = "0.11.2" }
protobuf = "3.2.0"
pprof = { version = "0.11.0", features = ["flamegraph", "protobuf-codec","frame-pointer"] }
q_compress = "0.11.1"
rand = "0.8"
regex = "1.5"
reqwest = { version = "0.11.11", features = ["json"] }
rustyline = "9.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serial_test = "0.8.0"
sled = "0.34.7"
snafu = "0.7"
snap = "1.0.0"
sys-info = "0.9.1"
static_assertions = "1.1"
surf = { version = "2.3.2", features = ["curl-client", "encoding"], default-features=false }
tempfile = "3"
tokio = { version = "1.21" }
tokio-stream = "0.1"
tokio-util = { version = "0.7.0" }
toml = "0.5.9"
tonic = "0.8"
tonic-build = "0.8"
tracing = "0.1.35"
tracing-futures = "0.2"
tracing-subscriber = "0.3.16"
tracing-appender = "0.2.2"
tracing-error = "0.2.0"
console-subscriber = "0.1.8"
url = "2.2"
uuid = { version = "1.1", features = ["v4"] }
ureq = { version = "2.5.0", features = ["json", "charset"] }
warp = { version = "0.3" }
walkdir = "2.3.2"
zstd = "0.11.2"
tikv-jemalloc-ctl = "0.5"
tikv-jemallocator = "0.5.0"
tikv-jemalloc-sys = { version = "0.5", features = ["stats", "profiling", "unprefixed_malloc_on_supported_platforms"] }
async-backtrace = "0.2.2"
radixdb = "0.2.5"
roaring = "0.10.1"
rust-crypto = "0.2.36"
tower = "0.4.13"

[workspace.package]
version = "2.2.0"
edition = "2021"

[profile.dev]
lto = false
opt-level = 0
codegen-units = 16
debug-assertions = true
panic = 'unwind'
incremental = true
overflow-checks = true
debug = true

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
debug-assertions = false
panic = 'unwind'
incremental = false
overflow-checks = false
debug = false

[profile.test]
lto = false
opt-level = 0
codegen-units = 16
debug-assertions = true
panic = 'unwind'
incremental = true
overflow-checks = true
debug = 2

[profile.test-ci]
inherits = "test"
incremental = true
overflow-checks = false
debug-assertions = false
panic = 'unwind'

[profile.bench]
lto = false
opt-level = 3
codegen-units = 1
debug-assertions = false
panic = 'unwind'
incremental = false
overflow-checks = false
debug = false
