[workspace]
members = [
    "common/models",
    "common/protos",
    "common/line_protocol",
    "common/metrics",
    "common/trace",
    "common/utils",
    "common/mem_allocator",
    "common/http_protocol",
    "query_server/spi",
    "query_server/query",
    "query_server/test",
    "e2e_test",
    "coordinator",
    "config",
    "tskv",
    "main",
    "client",
]
default-members = ["main"]

[workspace.dependencies]
async-trait = "0.1"
chrono = "0.4"
bincode = "1.3.3"
datafusion = { version = "13.0.0", features = ["scheduler"] }
flatbuffers = "2.1"
futures = { version = "0.3" }
libc = { version = "0.2", default-features = false }
parking_lot = { version = "0.12" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.7"
tokio = { version = "1.21" }

# exclude = ["client"]

[profile.dev]
lto = false
opt-level = 0
codegen-units = 16
debug-assertions = true
panic = 'unwind'
incremental = true
overflow-checks = true
debug = true

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
debug-assertions = false
panic = 'unwind'
incremental = false
overflow-checks = false
debug = false

[profile.test]
lto = false
opt-level = 0
codegen-units = 16
debug-assertions = true
panic = 'unwind'
incremental = true
overflow-checks = true
debug = 2

[profile.bench]
lto = false
opt-level = 3
codegen-units = 1
debug-assertions = false
panic = 'unwind'
incremental = false
overflow-checks = false
debug = false
