[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../common/models" }
config = { path = "../config" }
line_protocol = { path = "../common/line_protocol" }
protos = { path = "../common/protos" }
query = { path = "../query_server/query" }
trace = { path = "../common/trace" }
tskv = { path = "../tskv" }
spi = { path = "../query_server/spi" }
mem_allocator = { path = "../common/mem_allocator" }
metrics = { path = "../common/metrics" }
http_protocol = { path = "../common/http_protocol" }

async-stream = "0.3"
async-trait = { workspace = true }
backtrace = "0.3"
base64 = { version = "0.13" }
chrono = { workspace = true }
clap = { version = "3", features = ["derive", "env"] }
ctrlc = "3"
datafusion = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true, default-features = false, features = ["alloc"] }
lazy_static = "1.4"
libc = { workspace = true }
num_cpus = "1.13.0"
once_cell = { version = "1.4.0", features = ["parking_lot"] }
parking_lot = { workspace = true }
prost = "0.10"
regex = "1.5"
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true, features = [ "macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time" ] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.7", features = ["transport", "tls"] }
warp = { version = "0.3", features = ["tls"] }

[dev-dependencies]
reqwest = "0.11"
