[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3"
libc = { version = "0.2" }
log = "0.4"
num_cpus = "1.13.0"
clap = { version = "3", features = ["derive", "env"] }
once_cell = { version = "1.4.0", features = ["parking_lot"] }
tokio = { version = "1.13", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.0" }