[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }
protos = { path = "../protos" }
tskv = { path = "../tskv" }
async-stream = "0.3"
backtrace = "0.3"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
libc = { version = "0.2" }
log = "0.4"
num_cpus = "1.13.0"
clap = { version = "3", features = ["derive", "env"] }
flatbuffers = "2.1"
once_cell = { version = "1.4.0", features = ["parking_lot"] }
parking_lot = "0.12"
prost = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.13", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7.0" }
tonic = "0.7"
