[package]
name = "tskv"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
models = { path = "../common/models" }
metrics = {path = "../common/metrics"}
protos = { path = "../common/protos", features = ["test"] }
trace = { path = "../common/trace" }
utils = { path = "../common/utils" }

async-recursion = "1.0.0"
async-trait = { workspace = true }
bincode = {workspace = true}
bytes = "1.1"
bzip2 = "0.4.3"
chrono = { workspace = true}
core_affinity = "0.5.10"
crc32fast = "1.3.0"
crossbeam-channel = "0.5"
dashmap = "5.2"
datafusion = { workspace = true }
evmap = "10.0"
flatbuffers = { workspace = true }
flate2 = "1.0.24"
futures = { workspace = true, features = ["std", "thread-pool"] }
integer-encoding = "3.0.3"
lazy_static = "1.4"
libc = {workspace = true}
minivec = "0.4.0"
mio = "0.8"
num_cpus = "1.13.1"
num_enum = "0.5.7"
num-traits = "0.2.14"
once_cell = "1.10"
page_size = "0.4"
parking_lot = { workspace = true, features = ["nightly", "send_guard"] }
priority-queue = "1.2"
q_compress = "0.11.1"
regex = "1.5"
serde = { workspace = true }
serial_test = "0.8.0"
sled = "0.34.7"
snafu = { workspace = true }
snap = "1.0.0"
static_assertions = "1.1"
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.35"
walkdir = "2.3"
zstd = "0.11.2"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
rand = "0.8"
tempfile = "3"
parking_lot = { workspace = true, features = ["nightly"] }

[[bench]]
name = "kvcore_bench"
harness = false
