[package]
name = "tskv"
version = "0.1.0"
edition = "2021"

[dependencies]
protos = { path = "../protos" }
utils = {path = "../utils"}

chrono = "0.4"
core_affinity = "0.5.10"
crossbeam = "0.8.1"
futures = "0.3"
flatbuffers = "2.1"
lazy_static = "1.4"
libc = "0.2"
mio = "0.8"
num_cpus = "1.13.1"
once_cell = "1.10"
priority-queue = "1.2"
regex = "1.5"
snafu = "0.7"
tokio = { version = "1.17", features = ["full"] }
walkdir = "2.3"
async-trait = "0.1"
bytes = "1.1"
dashmap = "5.2"
evmap = "10.0"
page_size = "0.4"
parking_lot = "0.12"
static_assertions = "1.1"
hashbrown = "0.12.0"
crc32fast = "1.3.0"
serde = { version = "1.0.2", features = ["derive"] }
bincode = "1.3.3"
num-traits = "0.2.14"
num_enum = "0.5.7"

[dev-dependencies]
rand = "0.8"
tempfile = "3"
