# add user limit
max_users_number = 1
# create database limit
max_databases = 3
max_shard_number = 2
max_replicate_number = 2
max_retention_time = 30

[data_in_rate]
# 间隔时间内允许的流量，单位 B
refill = 5242880
# 初始流量 B
initial = 5242880
# 最大流量 B
max = 5242880
# 间隔 mill
interval = 300000

[data_out_rate]
refill = 5242880
initial = 5242880
max = 5242880
interval = 300000

[data_in_size]
count = 0

[data_out_size]
count = 0

# storage_size: CountLimiter,

[queries_rate]
refill = 500
initial = 500
max = 500
interval = 300000

[queries]
count = 0

[writes_rate]
refill = 5000
iniitial = 1000
max = 5000
interval = 300000

[writes]
count = 0
