dir = "/var/lib/cnosdb/meta"
retention-autocreate = true
hostname = ""

[HTTPD]
logging-enabled = true
http-bind-address = ":8091"
https-enabled = false
https-certificate = ""
election-timeout = "1s"
heartbeat-timeout = "1s"
leader-lease-timeout = "500ms"
commit-timeout = "50ms"
cluster-tracing = false
lease-duration = "1m0s"

[Log]
level = "INFO"
format = "text"
disable-timestamp = false
development = false
disable-caller = false
disable-stacktrace = false
disable-error-verbose = false
[Log.file]
filename = ""
max-size = 0
max-days = 0
max-backups = 0