[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[features]
test = []

[dependencies]
chrono = "0.4"
flatbuffers = "2.1"
prost = "0.10"
rand = "0.8"
tonic = "0.7"

[build-dependencies]
prost-build = "0.10"
tonic-build = "0.7"
