[application]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/$database/tsm/
# Directory for delta: $path/$database/delta/
path = 'dev/db'

[wal]
enabled = true
path = 'dev/wal'
sync = true

[summary]
max_summary_size = 134217728 # 128 * 1024 * 1024

[cache]
max_buffer_size = 1048576 # 134217728 # 128 * 1024 * 1024
max_immutable_number = 4

[storage]
max_level = 4
base_file_size = 16777216 # 16 * 1024 * 1024
compact_trigger = 4
max_compact_size = 2147483648 # 2 * 1024 * 1024 * 1024

[schema_store]
config_dir = 'dev/schema'
