
#reporting_disabled = false

[deployment]
#mode = 'singleton'
#cpu = 4
#memory = 16

[query]
max_server_connections = 10240
query_sql_limit = 16777216   # 16 * 1024 * 1024
write_sql_limit = 167772160   # 160 * 1024 * 1024
auth_enabled = false

[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/data/$database/tsm/
# Directory for delta: $path/data/$database/delta/
path = '/tmp/cnosdb/2001/db'
max_summary_size = "128M" # 134217728
base_file_size = "16M" # 16777216
flush_req_channel_cap = 16
compact_trigger_file_num = 4
compact_trigger_cold_duration = "1h"
max_compact_size = "2G" # 2147483648
max_concurrent_compaction = 4
strict_write = false

[wal]
enabled = true
path = '/tmp/cnosdb/2001/wal'
wal_req_channel_cap = 64
max_file_size = "1G" # 1073741824
flush_trigger_total_file_size = "2G" # 2147483648
sync = false
sync_interval = "0"

[cache]
max_buffer_size = "128M" # 134217728
max_immutable_number = 4

[log]
level = 'info'
path = '/tmp/cnosdb/2001/log'

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[cluster]
node_id = 2001
name = 'cluster_xxx'
meta_service_addr = '127.0.0.1:8901'

http_listen_addr = '127.0.0.1:8912'
grpc_listen_addr = '127.0.0.1:8913'
flight_rpc_listen_addr = '127.0.0.1:8914'
tcp_listen_addr = '127.0.0.1:8915'
store_metrics = true

[hinted_off]
enable = true
path = '/tmp/cnosdb/2001/hh'

