
#reporting_disabled = false

[query]
max_server_connections = 10240
query_sql_limit = 16777216   # 16 * 1024 * 1024
write_sql_limit = 167772160  # 160 * 1024 * 1024
auth_enabled = false

[storage]

# The directory where database files stored.
# Directory for summary:    $path/summary
# Directory for index:      $path/$database/data/id/index
# Directory for tsm:        $path/$database/data/id/tsm
# Directory for delta:      $path/$database/data/id/delta
path = 'data/db'

# The maximum file size of summary file.
max_summary_size = "128M" # 134217728

# The maximum file size of a level is:
# $base_file_size * level * $compact_trigger_file_num
base_file_size = "16M" # 16777216

# The maxmimum flush request in memory
flush_req_channel_cap = 16

# The maxmimum data file level (from 0 to 4).
max_level = 4

# Trigger of compaction using the number of level 0 files.
compact_trigger_file_num = 4

# Duration since last write to trigger compaction.
compact_trigger_cold_duration = "1h"

# The maximum size of all files in a compaction.
max_compact_size = "2G" # 2147483648

# The maximum concurrent compactions.
max_concurrent_compaction = 4

# If true, write request will not be checked in detail.
strict_write = false

[wal]
# The maxmimum wal request in memory
wal_req_channel_cap = 64

# If true, write requets on disk before writing to memory.
enabled = true

# The directory where write ahead logs stored.
path = 'data/wal'

# The maximum size of a wal file.
max_file_size = "1G" # 1073741824

# If true, fsync will be called after every wal writes.
sync = false
sync_interval = "0" # h, m, s

[cache]
max_buffer_size = "128M" # 134217728
max_immutable_number = 4

[log]
level = 'info'
path = 'data/log'

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[cluster]
node_id = 100
name = 'cluster_xxx'
meta_service_addr = '127.0.0.1:21001'

http_listen_addr = '127.0.0.1:31007'
grpc_listen_addr = '127.0.0.1:31008'
flight_rpc_listen_addr = '127.0.0.1:31006'

[hinted_off]
enable = true
path = '/tmp/cnosdb/hh'

