#[gloable-config]
tsfamily_num = 1
# DBOption
front_cpu = 2
back_cpu = 2
max_summary_size = 134217728 # 128 * 1024 * 1024
create_if_missing = false
db_path = "dev/db"
db_name =  "db"
#WalConfig
enabled = true
wal_config_dir = "dev/wal"
sync = true
#TseriesFamOpt
max_level =  4
level_ratio = 16
base_file_size = 16777216 # 16 * 1024 * 1024
compact_trigger = 4
max_compact_size = 2147483648 # 2 * 1024 * 1024 * 1024
tsm_dir = "dev/tsm/"
delta_dir = "dev/delta/"
index_path = "dev/idx"

max_memcache_size = 134217728 # 128 * 1024 * 1024
max_immemcache_num =  4
#SchemaStoreConfig
schema_store_config_dir = "dev/schema"

