[package]
name = "trace"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../../config" }
minitrace = { workspace = true }
minitrace-opentelemetry = { workspace = true }
time = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "registry",
    "time",
    "local-time",
] }
tracing-appender = { workspace = true }
tracing-error = { workspace = true }
console-subscriber = { workspace = true }
async-backtrace = { workspace = true, optional = true }
rand = { workspace = true }
chrono = { workspace = true }
snafu = { workspace = true }
itertools = { workspace = true }
http = { workspace = true }
tower = { workspace = true }
tonic = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }

[features]
default = []
backtrace = ["async-backtrace"]
