[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
protos = { path = "../../common/protos" }
trace = { path = "../../common/trace" }
tskv = { path = "../../tskv" }
models = { path = "../../common/models" }
config = { path = "../../config" }
spi = { path = "../spi" }

async-trait = { workspace = true }
datafusion = { workspace = true }
chrono = { workspace = true }
criterion = { version = "0.3.5", features = ["async_tokio"] }
crossbeam = "0.8"
flatbuffers = { workspace = true }
futures = { workspace = true }
minivec = "0.4.0"
num_cpus = "1"
parking_lot = { workspace = true }
paste = "1.0"
pin-project = "1.0"
priority-queue = "1.2.3"
tokio = { workspace = true, features = ["full"] }
tokio-util = { version = "0.7.0" }
rand = "0.8"
serde = { workspace = true }
sled = "0.34"
snafu = { workspace = true }

# use libc on unix like platforms to set worker priority in DedicatedExecutor
[target."cfg(unix)".dependencies.libc]
version = "0.2"

[[bench]]
harness = false
name = "aggregate_function"

[[bench]]
harness = false
name = "scalar_function"
