[package]
name = "spi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../../common/models" }
datafusion = { path = "../../common/datafusion_dep" }
snafu = { version = "0.7", features = ["backtraces"] }
async-trait = "0.1"
