[package]
name = "rpctests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.7.0"
protos = {path = "../protos"}

[dev-dependencies]
flatbuffers = "2.1"
tonic = "0.6"
tokio = { version = "1.17", features = ["full"] }
