name: Prepare Rust Builder
description: 'Prepare Rust Build Environment'
inputs:
  rust-version:
    description: 'version of rust to install (e.g. stable)'
    required: true
    default: 'stable'
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        curl -o flatbuffers.zip -sL https://github.com/google/flatbuffers/releases/download/v22.9.29/Linux.flatc.binary.clang++-12.zip
        unzip  flatbuffers.zip
        mv flatc /usr/local/bin
    - name: Setup Rust toolchain
      shell: bash
      run: |
        echo "Installing ${{ inputs.rust-version }}"
        source "$HOME/.cargo/env"
        rustup toolchain install ${{ inputs.rust-version }}
        rustup default ${{ inputs.rust-version }}
    - name: Install Protoc
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
    - name: Disable incremental compilation
      # Disable incremental compilation
      shell: bash
      run: echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
