name: Prepare Rust Builder
description: 'Prepare Rust Build Environment'
inputs:
  rust-version:
    description: 'version of rust to install (e.g. stable)'
    required: true
    default: 'stable'
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        git clone -b v22.9.29 --depth 1 https://github.com/google/flatbuffers.git
        cd flatbuffers
        cmake .
        make
        sudo make install
        sudo ldconfig
        flatc --version
    - name: Setup Rust toolchain
      shell: bash
      run: |
        echo "Installing ${{ inputs.rust-version }}"
        source "$HOME/.cargo/env"
        rustup toolchain install ${{ inputs.rust-version }}
        rustup default ${{ inputs.rust-version }}
    - name: Install Protoc
      shell: bash
      run: |
        sudo apt install apt-transport-https curl gnupg -y
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
        sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update
        sudo apt install g++ git bazel
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git submodule update --init --recursive
        bazel build :protoc :protobuf
        cp bazel-bin/protoc /usr/local/bin
