name: Prepare Rust Builder
description: 'Prepare Rust Build Environment'
runs:
  using: "composite"
  steps:
    - name: clean pkg
      shell: bash
      run: |
        bash ./.github/tools/free_disk_space.sh
    - name: Install Build Dependencies
      shell: bash
      run: |
        curl -o flatbuffers.zip -sL https://github.com/google/flatbuffers/releases/download/v22.9.29/Linux.flatc.binary.clang++-12.zip
        unzip  flatbuffers.zip
        mv flatc /usr/local/bin
    - name: Install Protoc
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
    - name: Install psmisc
      # killall
      shell: bash
      run: |
        sudo apt-get install -y psmisc
    - name: Disable incremental compilation
      # Disable incremental compilation
      shell: bash
      run: echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - uses: rui314/setup-mold@v1

    - name: Fixup git permissions
      # https://github.com/actions/checkout/issues/766
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Enable backtraces
      shell: bash
      run: echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
