[package]
name = "utils"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tikv-jemalloc-ctl = { workspace = true }
pprof = { workspace = true, features = ["flamegraph", "protobuf-codec","frame-pointer"] }



[dev-dependencies]
rand = {workspace = true}
