name: community-tag docker build and push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cnosdb' && github.repository == 'cnosdb/cnosdb' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          #platforms: linux/amd64,linux/arm64
          push: true
          tags: cnosdb/cnosdb:community-${{ github.event.inputs.tag }}
          build-args: |
            git_hash=${{ github.sha }}
      -
        name: modify dockerfile
        shell: bash
        run: |
          sed -i 's/\[tag\]/${{ github.event.inputs.tag }}/g' Dockerfile_for_k8s
      -
        name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      -
        name: Build and push k8s
        shell: bash
        run: |
          docker build -f Dockerfile_for_k8s -t registry.cn-hangzhou.aliyuncs.com/cnosdb/cnosdb-k8s:community-${{ github.event.inputs.tag }} .
          docker push registry.cn-hangzhou.aliyuncs.com/cnosdb/cnosdb-k8s:community-${{ github.event.inputs.tag }}
      -
        name: recover dockerfile
        shell: bash
        run: |
          sed -i 's/${{ github.event.inputs.tag }}/\[tag\]/g' Dockerfile_for_k8s
