name: community-tag docker build and push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  docker:
    strategy:
      matrix:
        image:
          - cnosdb
          - cnosdb-meta
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cnosdb' && github.repository == 'cnosdb/cnosdb' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: matrix.image == 'cnosdb'
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cnosdb/cnosdb:community-${{ github.event.inputs.tag }}
          file: docker/Dockerfile
          build-args: |
            git_hash=${{ github.sha }}
      -
        name: Build and push meta
        if: matrix.image == 'cnosdb-meta'
        id: docker_build_meta
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cnosdb/cnosdb:meta-community-${{ github.event.inputs.tag }}
          file: docker/Dockerfile_meta
          build-args: |
            git_hash=${{ github.sha }}
