name: community-latest docker build and push

on:
  schedule:
    - cron: "00 10 * * 1-5"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cnosdb' && github.repository == 'cnosdb/cnosdb' && github.ref == 'refs/heads/main'
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          #platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cnosdb/cnosdb:community-latest
            cnosdb/cnosdb:${{ steps.date.outputs.today }}
          build-args: |
            git_hash=${{ github.sha }}
      -
        name: modify dockerfile
        shell: bash
        run: |
          sed -i 's/\[tag\]/latest/g' Dockerfile_for_k8s
      -
        name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      -
        name: Build and push k8s
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/cnosdb/cnosdb-k8s:community-latest
            registry.cn-hangzhou.aliyuncs.com/cnosdb/cnosdb-k8s:${{ steps.date.outputs.today }}
          file: Dockerfile_for_k8s
      -
        name: recover dockerfile
        shell: bash
        run: |
          sed -i 's/latest/\[tag\]/g' Dockerfile_for_k8s
