name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        rust: [nightly]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install clippy rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt --toolchain nightly
      - name: Run
        run: |
          make clippy_check
          make fmt_check

  unit-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable ]

    steps:
    - uses: actions/checkout@v3

    - name: Prepare Rust Builder
      uses: ./.github/actions/setup-builder
      with:
          rust-version: ${{ matrix.rust }}

    - name: start meta
      shell: bash
      run: |
        bash ./meta/singleton.sh

    - name: test
      run: make test

    - name: clean
      run: make clean

  integration-test:
    name: "Integration Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ matrix.rust }}

      - name: start meta
        shell: bash
        run: |
          bash ./meta/singleton.sh
      - name: Test
        shell: bash
        run: |
          bash ./query_server/test/script/start_and_test.sh

