name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: Setup Rust toolchain
        shell: bash
        run: |
          echo "Installing nightly"
          rustup toolchain install nightly
          rustup default nightly
      - name: Install clippy rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt --toolchain nightly
      - name: Run
        run: |
          make clippy_check
          make fmt_check

  unit-test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: start meta
        shell: bash
        run: |
          bash ./meta/singleton.sh
      - name: test
        run: make test
      - name: clean
        run: make clean
      - name: trace
        run: make build_trace

  integration-test:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: start meta
        shell: bash
        run: |
          bash ./meta/singleton.sh
      - name: Test
        shell: bash
        run: |
          bash ./query_server/test/script/start_and_test.sh

  integration-test-singleton:
    name: "Integration Test Singleton"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: Test
        shell: bash
        run: |
          bash ./query_server/test/script/start_and_test.sh --singleton

  integration-test-3meta:
    name: "Integration Test 3meta"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: Test
        shell: bash
        run: |
          cd meta && cargo test --features=meta_e2e_test tests -- --test-threads  1

  integration-test-3m2d:
    name: "Integration Test 3meta 2data cluster"
    runs-on: ubuntu-4c16g
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: Test
        shell: bash
        run: |
          bash ./query_server/test/script/start_and_test_all.sh 3meta2data

  integration-test-Separation-of-storage-and-computing:
    name: "Integration Test Separation of storage and computing"
    runs-on: ubuntu-4c16g
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
      - name: Test
        shell: bash
        run: |
          bash ./query_server/test/script/start_and_test_all.sh 3meta_2data_1query_1tskv
  
